config/routes.rb
Rails.application.routes.draw do

  root 'users#index'


  resources :jobs
  # resources :users
  # get 'users' => 'users#login'
  # post 'users' => 'users#login'

  get 'users/index'
  post 'users/login'
  get 'users/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true, uniqueness: true

    has_many :jobs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    if check_session?
      @jobs = Job.all
    else
      redirect_to '/users/index'
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    if !check_session?
      redirect_to '/users/index'
    end
  end

  # GET /jobs/new
  def new
    if !check_session?
      redirect_to '/users/index'
    end
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    if !check_session?
      redirect_to '/users/index'
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create
    if !check_session?
      redirect_to '/users/index'
    end
    @job = Job.new(job_params)

    #Get User_id from session and store it
    @job.user_id = session["id"]

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    if !check_session?
      redirect_to '/users/index'
    end
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    if !check_session?
      redirect_to '/users/index'
    end
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :opening_date, :closing_date)
    end

    def check_session?
        if session["id"] != nil
            return true
        end
        return false
    end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb

class UsersController < ApplicationController

    def index
        if check_session?
            redirect_to '/jobs'
        end
    end

    def login
        email = params[:email]
        password = params[:password]

        user = User.find_by_email(params[:email])
        if user && password == user.password
            session["id"] = user.id
            redirect_to '/jobs'

        else
            redirect_to '/users/index'
        end

    end

    def destroy
        if session["id"] != nil
            session["id"] = nil
            redirect_to '/users/index'
        end
    end

    private
    def check_session?
        if session["id"] != nil
            return true
        end
        return false
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :opening_date %>
    <%= form.datetime_select :opening_date %>
  </div>

  <div class="field">
    <%= form.label :closing_date %>
    <%= form.datetime_select :closing_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Listing</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Opening date</th>
      <th>Closing date</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.opening_date.strftime("%B %e, %Y") %></td>
        <td><%= job.closing_date.strftime("%B %e, %Y") %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Opening date:</strong>
  <%= @job.opening_date.strftime("%B %e, %Y") %>
</p>

<p>
  <strong>Closing date:</strong>
  <%= @job.closing_date.strftime("%B %e, %Y") %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if session["id"] != nil %>
      <%= link_to 'Logout', users_destroy_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Login</h1>

  <%= form_tag( '/users/login') do |f| %>

  Email: <%= text_field_tag :email %>
  Password: <%= password_field_tag :password %>
  <%= submit_tag "Submit" %>
<% end %>